# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kmain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtLog = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.gridLayout_2.addWidget(self.txtLog, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkIsHex = QtWidgets.QCheckBox(self.tab_5)
        self.chkIsHex.setObjectName("chkIsHex")
        self.horizontalLayout_2.addWidget(self.chkIsHex)
        self.rdobase64_encode = QtWidgets.QRadioButton(self.tab_5)
        self.rdobase64_encode.setChecked(True)
        self.rdobase64_encode.setObjectName("rdobase64_encode")
        self.horizontalLayout_2.addWidget(self.rdobase64_encode)
        self.rdobase64_decode = QtWidgets.QRadioButton(self.tab_5)
        self.rdobase64_decode.setObjectName("rdobase64_decode")
        self.horizontalLayout_2.addWidget(self.rdobase64_decode)
        self.btnbase64_calc = QtWidgets.QPushButton(self.tab_5)
        self.btnbase64_calc.setObjectName("btnbase64_calc")
        self.horizontalLayout_2.addWidget(self.btnbase64_calc)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 8, 2, 1, 1)
        self.txtbase64_key = QtWidgets.QLineEdit(self.tab_5)
        self.txtbase64_key.setObjectName("txtbase64_key")
        self.gridLayout_8.addWidget(self.txtbase64_key, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 7, 0, 1, 1)
        self.txtbase64_output = QtWidgets.QPlainTextEdit(self.tab_5)
        self.txtbase64_output.setReadOnly(True)
        self.txtbase64_output.setObjectName("txtbase64_output")
        self.gridLayout_8.addWidget(self.txtbase64_output, 7, 2, 1, 1)
        self.txtbase64_input = QtWidgets.QPlainTextEdit(self.tab_5)
        self.txtbase64_input.setObjectName("txtbase64_input")
        self.gridLayout_8.addWidget(self.txtbase64_input, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtbase64file = QtWidgets.QLineEdit(self.tab_5)
        self.txtbase64file.setObjectName("txtbase64file")
        self.horizontalLayout_3.addWidget(self.txtbase64file)
        self.btnSelect = QtWidgets.QPushButton(self.tab_5)
        self.btnSelect.setObjectName("btnSelect")
        self.horizontalLayout_3.addWidget(self.btnSelect)
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.txturl_input = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txturl_input.setObjectName("txturl_input")
        self.gridLayout_12.addWidget(self.txturl_input, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.txturl_output = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.txturl_output.setReadOnly(True)
        self.txturl_output.setObjectName("txturl_output")
        self.gridLayout_13.addWidget(self.txturl_output, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_6)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rdourl_encode = QtWidgets.QRadioButton(self.frame)
        self.rdourl_encode.setChecked(True)
        self.rdourl_encode.setObjectName("rdourl_encode")
        self.horizontalLayout.addWidget(self.rdourl_encode)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_11.addWidget(self.frame, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tabWidget_3.addTab(self.tab_20, "")
        self.gridLayout_4.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btngdb32 = QtWidgets.QPushButton(self.groupBox_3)
        self.btngdb32.setMinimumSize(QtCore.QSize(50, 60))
        self.btngdb32.setMaximumSize(QtCore.QSize(160, 50))
        self.btngdb32.setObjectName("btngdb32")
        self.gridLayout_3.addWidget(self.btngdb32, 1, 0, 1, 1)
        self.btnida64 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnida64.setMinimumSize(QtCore.QSize(50, 60))
        self.btnida64.setMaximumSize(QtCore.QSize(160, 50))
        self.btnida64.setObjectName("btnida64")
        self.gridLayout_3.addWidget(self.btnida64, 0, 1, 1, 1)
        self.btngdb64 = QtWidgets.QPushButton(self.groupBox_3)
        self.btngdb64.setMinimumSize(QtCore.QSize(50, 60))
        self.btngdb64.setMaximumSize(QtCore.QSize(160, 50))
        self.btngdb64.setObjectName("btngdb64")
        self.gridLayout_3.addWidget(self.btngdb64, 1, 1, 1, 1)
        self.btnida32 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnida32.setMinimumSize(QtCore.QSize(50, 60))
        self.btnida32.setMaximumSize(QtCore.QSize(160, 50))
        self.btnida32.setObjectName("btnida32")
        self.gridLayout_3.addWidget(self.btnida32, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btnfrida32_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btnfrida32_2.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida32_2.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida32_2.setObjectName("btnfrida32_2")
        self.gridLayout_10.addWidget(self.btnfrida32_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnfrida32 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnfrida32.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida32.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida32.setObjectName("btnfrida32")
        self.gridLayout_9.addWidget(self.btnfrida32, 0, 0, 1, 1)
        self.btnfrida64 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnfrida64.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida64.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida64.setObjectName("btnfrida64")
        self.gridLayout_9.addWidget(self.btnfrida64, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.tabWidget_4.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tabWidget_4.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tabWidget_4.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.tabWidget_4.addTab(self.tab_22, "")
        self.gridLayout_6.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionexit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.btnbase64_calc.clicked.connect(MainWindow.base64_calc)
        self.txtbase64_input.textChanged.connect(MainWindow.base64_input_change)
        self.btnSelect.clicked.connect(MainWindow.select_file)
        self.pushButton.clicked.connect(MainWindow.save_file)
        self.chkIsHex.toggled['bool'].connect(MainWindow.hex_toggled)
        self.txturl_input.textChanged.connect(MainWindow.url_input_change)
        self.pushButton_2.clicked.connect(MainWindow.url_calc)
        self.btnfrida32_2.clicked.connect(MainWindow.reinstall_android)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "kTools"))
        self.groupBox.setTitle(_translate("MainWindow", "日志"))
        self.chkIsHex.setText(_translate("MainWindow", "16进制显示"))
        self.rdobase64_encode.setText(_translate("MainWindow", "encode"))
        self.rdobase64_decode.setText(_translate("MainWindow", "decode"))
        self.btnbase64_calc.setText(_translate("MainWindow", "计算"))
        self.txtbase64_key.setText(_translate("MainWindow", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"))
        self.label_2.setText(_translate("MainWindow", "密钥:"))
        self.label.setText(_translate("MainWindow", "输入数据:"))
        self.label_3.setText(_translate("MainWindow", "输出数据:"))
        self.label_4.setText(_translate("MainWindow", "文件名:"))
        self.btnSelect.setText(_translate("MainWindow", "选择"))
        self.pushButton.setText(_translate("MainWindow", "保存"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "base64"))
        self.groupBox_5.setTitle(_translate("MainWindow", "input"))
        self.groupBox_6.setTitle(_translate("MainWindow", "output"))
        self.rdourl_encode.setText(_translate("MainWindow", "encode"))
        self.radioButton_2.setText(_translate("MainWindow", "decode"))
        self.pushButton_2.setText(_translate("MainWindow", "计算"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "url"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "hexdump"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "javascript"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "编码处理"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "crc32"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "adler32"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "aes"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "md5"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "sha"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("MainWindow", "sm4"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), _translate("MainWindow", "rsa"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_20), _translate("MainWindow", "hmac"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "算法相关"))
        self.groupBox_3.setTitle(_translate("MainWindow", "调试"))
        self.btngdb32.setText(_translate("MainWindow", "gdb32"))
        self.btnida64.setText(_translate("MainWindow", "ida64"))
        self.btngdb64.setText(_translate("MainWindow", "gdb64"))
        self.btnida32.setText(_translate("MainWindow", "ida32"))
        self.groupBox_4.setTitle(_translate("MainWindow", "常用工具"))
        self.btnfrida32_2.setText(_translate("MainWindow", "adb环境安装"))
        self.groupBox_2.setTitle(_translate("MainWindow", "hook"))
        self.btnfrida32.setText(_translate("MainWindow", "frida32"))
        self.btnfrida64.setText(_translate("MainWindow", "frida64"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "常用脚本"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("MainWindow", "binformat"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_17), _translate("MainWindow", "array"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("MainWindow", "zlib"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("MainWindow", "varint"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), _translate("MainWindow", "oct"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_22), _translate("MainWindow", "protobuf"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "常用工具"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionexit.setText(_translate("MainWindow", "exit"))

