# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kmain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 702)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtLog = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.gridLayout_2.addWidget(self.txtLog, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_16)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.txtbinformat_input = QtWidgets.QPlainTextEdit(self.groupBox_10)
        self.txtbinformat_input.setObjectName("txtbinformat_input")
        self.gridLayout_18.addWidget(self.txtbinformat_input, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.txtbinformat_output = QtWidgets.QPlainTextEdit(self.groupBox_11)
        self.txtbinformat_output.setReadOnly(True)
        self.txtbinformat_output.setObjectName("txtbinformat_output")
        self.gridLayout_19.addWidget(self.txtbinformat_output, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab_16)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.lbbinformat_cnt = QtWidgets.QLabel(self.frame_2)
        self.lbbinformat_cnt.setObjectName("lbbinformat_cnt")
        self.gridLayout_20.addWidget(self.lbbinformat_cnt, 0, 1, 1, 1)
        self.rdohex2str = QtWidgets.QRadioButton(self.frame_2)
        self.rdohex2str.setObjectName("rdohex2str")
        self.gridLayout_20.addWidget(self.rdohex2str, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_20.addWidget(self.label_7, 0, 0, 1, 1)
        self.btnbinformat = QtWidgets.QPushButton(self.frame_2)
        self.btnbinformat.setMinimumSize(QtCore.QSize(100, 50))
        self.btnbinformat.setMaximumSize(QtCore.QSize(120, 50))
        self.btnbinformat.setObjectName("btnbinformat")
        self.gridLayout_20.addWidget(self.btnbinformat, 0, 4, 1, 1)
        self.rdostr2hex = QtWidgets.QRadioButton(self.frame_2)
        self.rdostr2hex.setChecked(True)
        self.rdostr2hex.setObjectName("rdostr2hex")
        self.gridLayout_20.addWidget(self.rdostr2hex, 0, 2, 1, 1)
        self.gridLayout_15.addWidget(self.frame_2, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.txthexdump_input = QtWidgets.QPlainTextEdit(self.groupBox_12)
        self.txthexdump_input.setObjectName("txthexdump_input")
        self.gridLayout_21.addWidget(self.txthexdump_input, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_12, 0, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_7)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.txthexdump_output = QtWidgets.QPlainTextEdit(self.groupBox_13)
        self.txthexdump_output.setReadOnly(True)
        self.txthexdump_output.setObjectName("txthexdump_output")
        self.gridLayout_22.addWidget(self.txthexdump_output, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab_7)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cmbhexdump = QtWidgets.QComboBox(self.frame_3)
        self.cmbhexdump.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cmbhexdump.setObjectName("cmbhexdump")
        self.cmbhexdump.addItem("")
        self.cmbhexdump.addItem("")
        self.cmbhexdump.addItem("")
        self.cmbhexdump.addItem("")
        self.cmbhexdump.setItemText(3, "")
        self.horizontalLayout_4.addWidget(self.cmbhexdump)
        self.gridLayout_41.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.btnhexdump_calc = QtWidgets.QPushButton(self.frame_3)
        self.btnhexdump_calc.setMinimumSize(QtCore.QSize(0, 50))
        self.btnhexdump_calc.setMaximumSize(QtCore.QSize(120, 50))
        self.btnhexdump_calc.setObjectName("btnhexdump_calc")
        self.gridLayout_41.addWidget(self.btnhexdump_calc, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.frame_3, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_23.setObjectName("groupBox_23")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.groupBox_23)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.txtasm_input = QtWidgets.QPlainTextEdit(self.groupBox_23)
        self.txtasm_input.setObjectName("txtasm_input")
        self.gridLayout_35.addWidget(self.txtasm_input, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_23, 0, 0, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_22.setObjectName("groupBox_22")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.groupBox_22)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.txtasm_output = QtWidgets.QPlainTextEdit(self.groupBox_22)
        self.txtasm_output.setReadOnly(True)
        self.txtasm_output.setObjectName("txtasm_output")
        self.gridLayout_34.addWidget(self.txtasm_output, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_22, 1, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.tab_8)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.cmbasm = QtWidgets.QComboBox(self.frame_8)
        self.cmbasm.setMaximumSize(QtCore.QSize(300, 16777215))
        self.cmbasm.setObjectName("cmbasm")
        self.cmbasm.addItem("")
        self.cmbasm.addItem("")
        self.horizontalLayout_6.addWidget(self.cmbasm)
        self.gridLayout_27.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.btnzlib_calc_5 = QtWidgets.QPushButton(self.frame_8)
        self.btnzlib_calc_5.setMinimumSize(QtCore.QSize(0, 50))
        self.btnzlib_calc_5.setMaximumSize(QtCore.QSize(120, 50))
        self.btnzlib_calc_5.setObjectName("btnzlib_calc_5")
        self.gridLayout_27.addWidget(self.btnzlib_calc_5, 0, 1, 1, 1)
        self.gridLayout_36.addWidget(self.frame_8, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_8, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_18)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.txtzlib_input = QtWidgets.QPlainTextEdit(self.groupBox_15)
        self.txtzlib_input.setObjectName("txtzlib_input")
        self.gridLayout_24.addWidget(self.txtzlib_input, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.txtzlib_output = QtWidgets.QPlainTextEdit(self.groupBox_14)
        self.txtzlib_output.setReadOnly(True)
        self.txtzlib_output.setObjectName("txtzlib_output")
        self.gridLayout_23.addWidget(self.txtzlib_output, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_14, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab_18)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rdozlib = QtWidgets.QRadioButton(self.frame_4)
        self.rdozlib.setChecked(True)
        self.rdozlib.setObjectName("rdozlib")
        self.horizontalLayout_5.addWidget(self.rdozlib)
        self.rdounzlib = QtWidgets.QRadioButton(self.frame_4)
        self.rdounzlib.setObjectName("rdounzlib")
        self.horizontalLayout_5.addWidget(self.rdounzlib)
        self.chkzlib_ishex = QtWidgets.QCheckBox(self.frame_4)
        self.chkzlib_ishex.setObjectName("chkzlib_ishex")
        self.horizontalLayout_5.addWidget(self.chkzlib_ishex)
        self.gridLayout_37.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.btnzlib_calc = QtWidgets.QPushButton(self.frame_4)
        self.btnzlib_calc.setMinimumSize(QtCore.QSize(0, 50))
        self.btnzlib_calc.setMaximumSize(QtCore.QSize(120, 50))
        self.btnzlib_calc.setObjectName("btnzlib_calc")
        self.gridLayout_37.addWidget(self.btnzlib_calc, 0, 1, 1, 1)
        self.gridLayout_17.addWidget(self.frame_4, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_18, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_21)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_21)
        self.groupBox_19.setObjectName("groupBox_19")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_19)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.txtoct_input = QtWidgets.QPlainTextEdit(self.groupBox_19)
        self.txtoct_input.setObjectName("txtoct_input")
        self.gridLayout_29.addWidget(self.txtoct_input, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_19, 0, 0, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_21)
        self.groupBox_18.setObjectName("groupBox_18")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_18)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.txtoct_output = QtWidgets.QPlainTextEdit(self.groupBox_18)
        self.txtoct_output.setReadOnly(True)
        self.txtoct_output.setObjectName("txtoct_output")
        self.gridLayout_28.addWidget(self.txtoct_output, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_18, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_21)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.btnoct_calc = QtWidgets.QPushButton(self.frame_6)
        self.btnoct_calc.setMinimumSize(QtCore.QSize(0, 50))
        self.btnoct_calc.setMaximumSize(QtCore.QSize(120, 50))
        self.btnoct_calc.setObjectName("btnoct_calc")
        self.gridLayout_26.addWidget(self.btnoct_calc, 0, 0, 1, 1)
        self.gridLayout_30.addWidget(self.frame_6, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.tab_22)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_22)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.txtprotoc_input = QtWidgets.QPlainTextEdit(self.groupBox_21)
        self.txtprotoc_input.setObjectName("txtprotoc_input")
        self.gridLayout_32.addWidget(self.txtprotoc_input, 0, 0, 1, 1)
        self.gridLayout_33.addWidget(self.groupBox_21, 0, 0, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_22)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.txtprotoc_output = QtWidgets.QPlainTextEdit(self.groupBox_20)
        self.txtprotoc_output.setReadOnly(True)
        self.txtprotoc_output.setObjectName("txtprotoc_output")
        self.gridLayout_31.addWidget(self.txtprotoc_output, 0, 0, 1, 1)
        self.gridLayout_33.addWidget(self.groupBox_20, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.tab_22)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.btnprotoc_calc = QtWidgets.QPushButton(self.frame_7)
        self.btnprotoc_calc.setMinimumSize(QtCore.QSize(0, 50))
        self.btnprotoc_calc.setMaximumSize(QtCore.QSize(120, 50))
        self.btnprotoc_calc.setObjectName("btnprotoc_calc")
        self.gridLayout_25.addWidget(self.btnprotoc_calc, 0, 0, 1, 1)
        self.gridLayout_33.addWidget(self.frame_7, 2, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_22, "")
        self.gridLayout_6.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tabWidget_3.addTab(self.tab_20, "")
        self.gridLayout_4.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkHexInput = QtWidgets.QCheckBox(self.tab_5)
        self.chkHexInput.setObjectName("chkHexInput")
        self.horizontalLayout_2.addWidget(self.chkHexInput)
        self.chkHexOutput = QtWidgets.QCheckBox(self.tab_5)
        self.chkHexOutput.setObjectName("chkHexOutput")
        self.horizontalLayout_2.addWidget(self.chkHexOutput)
        self.rdobase64_encode = QtWidgets.QRadioButton(self.tab_5)
        self.rdobase64_encode.setChecked(True)
        self.rdobase64_encode.setObjectName("rdobase64_encode")
        self.horizontalLayout_2.addWidget(self.rdobase64_encode)
        self.rdobase64_decode = QtWidgets.QRadioButton(self.tab_5)
        self.rdobase64_decode.setObjectName("rdobase64_decode")
        self.horizontalLayout_2.addWidget(self.rdobase64_decode)
        self.btnbase64_calc = QtWidgets.QPushButton(self.tab_5)
        self.btnbase64_calc.setObjectName("btnbase64_calc")
        self.horizontalLayout_2.addWidget(self.btnbase64_calc)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 8, 2, 1, 1)
        self.txtbase64_key = QtWidgets.QLineEdit(self.tab_5)
        self.txtbase64_key.setObjectName("txtbase64_key")
        self.gridLayout_8.addWidget(self.txtbase64_key, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 7, 0, 1, 1)
        self.txtbase64_output = QtWidgets.QPlainTextEdit(self.tab_5)
        self.txtbase64_output.setReadOnly(True)
        self.txtbase64_output.setObjectName("txtbase64_output")
        self.gridLayout_8.addWidget(self.txtbase64_output, 7, 2, 1, 1)
        self.txtbase64_input = QtWidgets.QPlainTextEdit(self.tab_5)
        self.txtbase64_input.setObjectName("txtbase64_input")
        self.gridLayout_8.addWidget(self.txtbase64_input, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtbase64file = QtWidgets.QLineEdit(self.tab_5)
        self.txtbase64file.setObjectName("txtbase64file")
        self.horizontalLayout_3.addWidget(self.txtbase64file)
        self.btnSelect = QtWidgets.QPushButton(self.tab_5)
        self.btnSelect.setObjectName("btnSelect")
        self.horizontalLayout_3.addWidget(self.btnSelect)
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.txturl_input = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.txturl_input.setObjectName("txturl_input")
        self.gridLayout_12.addWidget(self.txturl_input, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.txturl_output = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.txturl_output.setReadOnly(True)
        self.txturl_output.setObjectName("txturl_output")
        self.gridLayout_13.addWidget(self.txturl_output, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab_6)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rdourl_encode = QtWidgets.QRadioButton(self.frame)
        self.rdourl_encode.setChecked(True)
        self.rdourl_encode.setObjectName("rdourl_encode")
        self.horizontalLayout.addWidget(self.rdourl_encode)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(120, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_11.addWidget(self.frame, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_17)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_24.setObjectName("groupBox_24")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.groupBox_24)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.txtvarint_input = QtWidgets.QPlainTextEdit(self.groupBox_24)
        self.txtvarint_input.setObjectName("txtvarint_input")
        self.gridLayout_38.addWidget(self.txtvarint_input, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.groupBox_24, 0, 0, 1, 1)
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_25.setObjectName("groupBox_25")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.groupBox_25)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.txtvarint_output = QtWidgets.QPlainTextEdit(self.groupBox_25)
        self.txtvarint_output.setReadOnly(True)
        self.txtvarint_output.setObjectName("txtvarint_output")
        self.gridLayout_39.addWidget(self.txtvarint_output, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.groupBox_25, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.tab_17)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.btnvarint_calc = QtWidgets.QPushButton(self.frame_9)
        self.btnvarint_calc.setGeometry(QtCore.QRect(502, 10, 120, 50))
        self.btnvarint_calc.setMinimumSize(QtCore.QSize(0, 50))
        self.btnvarint_calc.setMaximumSize(QtCore.QSize(120, 50))
        self.btnvarint_calc.setObjectName("btnvarint_calc")
        self.gridLayout_40.addWidget(self.frame_9, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_17, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_7.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtPid = QtWidgets.QLineEdit(self.groupBox_7)
        self.txtPid.setObjectName("txtPid")
        self.gridLayout_3.addWidget(self.txtPid, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_7, 0, 0, 2, 1)
        self.btnida32 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnida32.setMinimumSize(QtCore.QSize(50, 60))
        self.btnida32.setMaximumSize(QtCore.QSize(160, 50))
        self.btnida32.setObjectName("btnida32")
        self.gridLayout_14.addWidget(self.btnida32, 0, 1, 1, 1)
        self.btnida64 = QtWidgets.QPushButton(self.groupBox_3)
        self.btnida64.setMinimumSize(QtCore.QSize(50, 60))
        self.btnida64.setMaximumSize(QtCore.QSize(160, 50))
        self.btnida64.setObjectName("btnida64")
        self.gridLayout_14.addWidget(self.btnida64, 0, 2, 1, 1)
        self.btngdb32 = QtWidgets.QPushButton(self.groupBox_3)
        self.btngdb32.setMinimumSize(QtCore.QSize(50, 60))
        self.btngdb32.setMaximumSize(QtCore.QSize(160, 50))
        self.btngdb32.setObjectName("btngdb32")
        self.gridLayout_14.addWidget(self.btngdb32, 1, 1, 1, 1)
        self.btngdb64 = QtWidgets.QPushButton(self.groupBox_3)
        self.btngdb64.setMinimumSize(QtCore.QSize(50, 60))
        self.btngdb64.setMaximumSize(QtCore.QSize(160, 50))
        self.btngdb64.setObjectName("btngdb64")
        self.gridLayout_14.addWidget(self.btngdb64, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btnfrida32_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.btnfrida32_2.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida32_2.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida32_2.setObjectName("btnfrida32_2")
        self.gridLayout_10.addWidget(self.btnfrida32_2, 0, 0, 1, 1)
        self.btnkill_debug = QtWidgets.QPushButton(self.groupBox_4)
        self.btnkill_debug.setMaximumSize(QtCore.QSize(160, 60))
        self.btnkill_debug.setObjectName("btnkill_debug")
        self.gridLayout_10.addWidget(self.btnkill_debug, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnfrida32 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnfrida32.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida32.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida32.setObjectName("btnfrida32")
        self.gridLayout_9.addWidget(self.btnfrida32, 0, 0, 1, 1)
        self.btnfrida64 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnfrida64.setMinimumSize(QtCore.QSize(50, 60))
        self.btnfrida64.setMaximumSize(QtCore.QSize(160, 50))
        self.btnfrida64.setObjectName("btnfrida64")
        self.gridLayout_9.addWidget(self.btnfrida64, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionexit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(2)
        self.btnfrida32_2.clicked.connect(MainWindow.reinstall_android)
        self.btnfrida32.clicked.connect(MainWindow.start_frida32)
        self.btnfrida64.clicked.connect(MainWindow.start_frida64)
        self.btnida32.clicked.connect(MainWindow.start_ida32)
        self.btnida64.clicked.connect(MainWindow.start_ida64)
        self.btngdb32.clicked.connect(MainWindow.start_gdb32)
        self.btngdb64.clicked.connect(MainWindow.start_gdb64)
        self.btnkill_debug.clicked.connect(MainWindow.kill_debug)
        self.txtbase64_input.textChanged.connect(MainWindow.base64_input_change)
        self.btnSelect.clicked.connect(MainWindow.select_file)
        self.btnbase64_calc.clicked.connect(MainWindow.base64_calc)
        self.pushButton.clicked.connect(MainWindow.save_file)
        self.chkHexOutput.toggled['bool'].connect(MainWindow.hex_toggled)
        self.txturl_input.textChanged.connect(MainWindow.url_input_change)
        self.pushButton_2.clicked.connect(MainWindow.url_calc)
        self.txtbinformat_input.textChanged.connect(MainWindow.binformat_input_change)
        self.btnbinformat.clicked.connect(MainWindow.binformat_calc)
        self.btnhexdump_calc.clicked.connect(MainWindow.hexdump_calc)
        self.txthexdump_input.textChanged.connect(MainWindow.hexdump_input_change)
        self.cmbhexdump.currentIndexChanged['QString'].connect(MainWindow.hexdump_cmb_change)
        self.btnzlib_calc.clicked.connect(MainWindow.zlib_calc)
        self.txtzlib_input.textChanged.connect(MainWindow.zlib_input_change)
        self.btnvarint_calc.clicked.connect(MainWindow.varint_calc)
        self.txtvarint_input.textChanged.connect(MainWindow.varint_input_change)
        self.btnoct_calc.clicked.connect(MainWindow.oct_calc)
        self.txtoct_input.textChanged.connect(MainWindow.oct_input_change)
        self.btnprotoc_calc.clicked.connect(MainWindow.protoc_calc)
        self.txtprotoc_input.textChanged.connect(MainWindow.protoc_input_change)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "kTools"))
        self.groupBox.setTitle(_translate("MainWindow", "日志"))
        self.tabWidget_4.setToolTip(_translate("MainWindow", "zlib编解码"))
        self.groupBox_10.setTitle(_translate("MainWindow", "input"))
        self.groupBox_11.setTitle(_translate("MainWindow", "output"))
        self.lbbinformat_cnt.setText(_translate("MainWindow", "0"))
        self.rdohex2str.setText(_translate("MainWindow", "hex2str"))
        self.label_7.setText(_translate("MainWindow", "长度："))
        self.btnbinformat.setToolTip(_translate("MainWindow", "字符串转16进制和16进制转字符串"))
        self.btnbinformat.setText(_translate("MainWindow", "计算"))
        self.rdostr2hex.setText(_translate("MainWindow", "str2hex"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("MainWindow", "str2hex"))
        self.groupBox_12.setTitle(_translate("MainWindow", "input"))
        self.groupBox_13.setTitle(_translate("MainWindow", "output"))
        self.label_6.setText(_translate("MainWindow", "输出类型："))
        self.cmbhexdump.setItemText(0, _translate("MainWindow", "空格分割"))
        self.cmbhexdump.setItemText(1, _translate("MainWindow", "逗号分割"))
        self.cmbhexdump.setItemText(2, _translate("MainWindow", "字节列表"))
        self.btnhexdump_calc.setToolTip(_translate("MainWindow", "匹配hexdump中间的字节部分出来"))
        self.btnhexdump_calc.setText(_translate("MainWindow", "计算"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("MainWindow", "hexdump"))
        self.groupBox_23.setTitle(_translate("MainWindow", "input"))
        self.groupBox_22.setTitle(_translate("MainWindow", "output"))
        self.label_8.setText(_translate("MainWindow", "汇编平台："))
        self.cmbasm.setItemText(0, _translate("MainWindow", "arm"))
        self.cmbasm.setItemText(1, _translate("MainWindow", "arm64"))
        self.btnzlib_calc_5.setToolTip(_translate("MainWindow", "汇编转二进制和二进制转汇编"))
        self.btnzlib_calc_5.setText(_translate("MainWindow", "计算"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "asm"))
        self.groupBox_15.setTitle(_translate("MainWindow", "input"))
        self.groupBox_14.setTitle(_translate("MainWindow", "output"))
        self.rdozlib.setText(_translate("MainWindow", "zlib"))
        self.rdounzlib.setText(_translate("MainWindow", "unzlib"))
        self.chkzlib_ishex.setText(_translate("MainWindow", "输入为16进制"))
        self.btnzlib_calc.setToolTip(_translate("MainWindow", "zlib压缩和解压"))
        self.btnzlib_calc.setText(_translate("MainWindow", "计算"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("MainWindow", "zlib"))
        self.groupBox_19.setTitle(_translate("MainWindow", "input"))
        self.groupBox_18.setTitle(_translate("MainWindow", "output"))
        self.btnoct_calc.setToolTip(_translate("MainWindow", "8进制字符串转中文"))
        self.btnoct_calc.setText(_translate("MainWindow", "计算"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), _translate("MainWindow", "oct"))
        self.groupBox_21.setTitle(_translate("MainWindow", "input"))
        self.groupBox_20.setTitle(_translate("MainWindow", "output"))
        self.btnprotoc_calc.setToolTip(_translate("MainWindow", "匹配hexdump中间的字节部分出来"))
        self.btnprotoc_calc.setText(_translate("MainWindow", "计算"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_22), _translate("MainWindow", "protobuf"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "常用工具"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "crc32"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "adler32"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "aes"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "md5"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "sha"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("MainWindow", "sm4"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), _translate("MainWindow", "rsa"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_20), _translate("MainWindow", "hmac"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "算法相关"))
        self.chkHexInput.setText(_translate("MainWindow", "16进制输入"))
        self.chkHexOutput.setText(_translate("MainWindow", "16进制显示"))
        self.rdobase64_encode.setText(_translate("MainWindow", "encode"))
        self.rdobase64_decode.setText(_translate("MainWindow", "decode"))
        self.btnbase64_calc.setText(_translate("MainWindow", "计算"))
        self.txtbase64_key.setText(_translate("MainWindow", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"))
        self.label_2.setText(_translate("MainWindow", "密钥:"))
        self.label.setText(_translate("MainWindow", "输入数据:"))
        self.label_3.setText(_translate("MainWindow", "输出数据:"))
        self.label_4.setText(_translate("MainWindow", "文件名:"))
        self.btnSelect.setText(_translate("MainWindow", "选择"))
        self.pushButton.setText(_translate("MainWindow", "保存"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "base64"))
        self.groupBox_5.setTitle(_translate("MainWindow", "input"))
        self.groupBox_6.setTitle(_translate("MainWindow", "output"))
        self.rdourl_encode.setText(_translate("MainWindow", "encode"))
        self.radioButton_2.setText(_translate("MainWindow", "decode"))
        self.pushButton_2.setText(_translate("MainWindow", "计算"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "url"))
        self.groupBox_24.setTitle(_translate("MainWindow", "input"))
        self.groupBox_25.setTitle(_translate("MainWindow", "output"))
        self.btnvarint_calc.setToolTip(_translate("MainWindow", "protobuf的varint转换"))
        self.btnvarint_calc.setText(_translate("MainWindow", "计算"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_17), _translate("MainWindow", "varint"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "编码处理"))
        self.groupBox_3.setTitle(_translate("MainWindow", "调试"))
        self.groupBox_7.setTitle(_translate("MainWindow", "进程信息(gdb用到)"))
        self.label_5.setText(_translate("MainWindow", "进程id："))
        self.btnida32.setText(_translate("MainWindow", "ida32"))
        self.btnida64.setText(_translate("MainWindow", "ida64"))
        self.btngdb32.setText(_translate("MainWindow", "gdb32"))
        self.btngdb64.setText(_translate("MainWindow", "gdb64"))
        self.groupBox_4.setTitle(_translate("MainWindow", "常用工具"))
        self.btnfrida32_2.setText(_translate("MainWindow", "adb环境安装"))
        self.btnkill_debug.setText(_translate("MainWindow", "一键杀调试进程"))
        self.groupBox_2.setTitle(_translate("MainWindow", "hook"))
        self.btnfrida32.setText(_translate("MainWindow", "frida32"))
        self.btnfrida64.setText(_translate("MainWindow", "frida64"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "常用脚本"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionexit.setText(_translate("MainWindow", "exit"))

